#
# Bases de Dados 2020/2021
# Trabalho Pr√°tico
#
# Authors:
#   Nuno Antunes <nmsa@dei.uc.pt>
#   BD 2021 Team - https://dei.uc.pt/lei/
#   University of Coimbra
version: "3"

services:
    leiloes:
        build: ./postgresql
        container_name: leiloes
        expose:
            - "5432"
        ports:
            - "5432:5432"
    web:
        build: ./python
        container_name: api
        volumes:
            - "./python/app:/app"
        expose:
            - "5000"
        ports:
            - "8080:5000"
        depends_on:
            - leiloes
